apiVersion: skaffold/v2beta23
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
    - image: ghcr.io/keptn-sandbox/keptn-gitea-provisioner-service
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    flags:
      upgrade: ["--reuse-values", "--install"]
    releases:
      - name: keptn-gitea-provisioner-service
        namespace: default
        artifactOverrides:
          image: ghcr.io/keptn-sandbox/keptn-gitea-provisioner-service
        imageStrategy:
          helm: { }
        overrides:
          gitea:
            admin:
              username: "GiteaAdmin"
              password: "GiteaAdmin"
          resources:
            limits:
              memory: 512Mi
        chartPath: chart
