{{ if .Values.gitea.admin.create }}
apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret
type: Opaque
stringData:
  username: {{ .Values.gitea.admin.username }}
  password: {{ .Values.gitea.admin.password }}
{{- end }}