{{ if .Values.gitea.admin.create }}
apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret
type: Opaque
data:
  username: {{ b64enc .Values.gitea.admin.username | quote }}
  password: {{ b64enc .Values.gitea.admin.password | quote }}
{{- end }}